version: '3'
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    links:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - "${MYSQL_PATH}:/var/lib/mysql"
